dist: bionic

language: python
python:
  - "2.7"
  - "3.7"

addons:
  apt:
    packages:
    - autoconf
    - automake
    - pkg-config
    - intltool
    - libglib2.0-dev
    - xsltproc
    - docbook-xsl
    - docbook-xml
    - iptables
    - ipset
    - ebtables
    - libxml2-utils
    - libdbus-1-dev
    - libgirepository1.0-dev

install:
  - pip install flake8 decorator dbus-python PyGObject
    && pushd /tmp
    && tar xf ${OLDPWD}/.travis/python-slip-0.6.5.tar.bz2
    && cd python-slip-0.6.5
    && make
    && pip install .
    && popd

script:
  - ./autogen.sh
    && ./configure --sysconfdir=/etc
    && make -j32
  - make -C src check-local
  - make -C config check-local
